default_stages: [commit-msg]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
